### ISSUE TITLE
Inspect python code to determine dependencies

### ISSUE THREAD

**Issue by costrouc** [nix-community/nixpkgs-pytools#11]
Inspect via the python ast to determine test dependencies, setup dependencies (build), and propagatedBuildDependencies.

This would not be fool proof but would provide a much better list of packages being used.

**Comment by makefu** [comment]
test dependencies are currently included as comments, it seems `nix-init` (https://github.com/nix-community/nix-init) currently handles the situation better. be sure to check out this project as well
