### ISSUE TITLE
python-package-init can't process utm package

### ISSUE THREAD

**Issue by alexvorobiev** [nix-community/nixpkgs-pytools#12]
Trying to import utm (https://github.com/Turbo87/utm):
```
$ python-package-init utm
utm None
usage: python-package-init [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: python-package-init --help [cmd1 cmd2 ...]
   or: python-package-init --help-commands
   or: python-package-init cmd --help

error: invalid command 'utm'
```

**Comment by costrouc** [comment]
Try running with a newer version of `nixpkgs-pytools` older versions has issues with this. It works for me with the newest version.

`nix-shell -p nixpkgs-pytools --run "python-package-init utm"`

Did that work for you?

**Comment by alexvorobiev** [comment]
Yes, that works, thanks!
