### ISSUE TITLE
Urls are unquoted 

### ISSUE THREAD

**Issue by tbenst** [nix-community/nixpkgs-pytools#16]
Per rfc 45, these should be quoted. Thanks for this awesome package!

**Comment by makefu** [comment]
Thanks!

**Comment by kini** [comment]
Thanks for fixing this! Could you please cut a new release version so we can get this fix into the version nixpkgs has? (By the way, the github "releases" for this repo only go up to 1.1.0 currently, though the git tags go up to 1.3.0.)
