### ISSUE TITLE
Moving python-package-init.py to seperate repository with tests

### ISSUE THREAD

**Issue by costrouc** [nix-community/nixpkgs-pytools#6]
As @FRidh mentioned a while back in https://github.com/costrouc/nixpkgs-dev-tools/pull/4#issuecomment-441103790 it would be worth moving this program to a separate repository with a focus on tooling for python development in nixpkgs with more testing. It seems that this program is being used. I certainly use it for all my python contributions but it still fails at times for me.

Thoughts on where this repository should be? I would like to move it out of a repository that I named "nixpkgs-dev-tools" as this is clearly not the focus of the repository and make the tool more accessible to the community, easier for others to find, and make changes.

cc: @FRidh @bhipple

**Comment by bhipple** [comment]
I'm OK with whatever you guys decide. `costrouc/nixpkgs-pytools` perhaps?

**Comment by makefu** [comment]
I find this tool super useful, as it avoids the overhead of pypi2nix by just guessing everything is packaged. Maybe the correct namespace would be in https://github.com/nix-community/ ?

**Comment by costrouc** [comment]
@makefu Yeah that would be a good place. This tools has saved me hours but it still fails on me at times. I'll contact nix-community and see if they can have this as a repo.

**Comment by makefu** [comment]
@costrouc let me do this for you :+1: 
Any idea about the new name?

cc @FRidh  @bhipple

**Comment by costrouc** [comment]
@makefu I would really appreciate that! I liked `nixpkgs-pytools` that @bhipple suggested as it would not limit the scope of the project to just `python-package-init.py`.

**Comment by makefu** [comment]
maybe we can package the script into a real python package and add it to nixpkgs. then we could run:
`nix-shell -p nixpkgs-pytools --run "python-package-init mypackage"`

**Comment by makefu** [comment]
i created the repo in the nix community namespace.

Edit: mh, it seems that the Issues and Pull Requiests were not transferred (obviously)... that only seems to happen when the owner is transferred. maybe we do this instead of forking?

**Comment by costrouc** [comment]
Great idea on `nix-shell -p nixpkgs-pytools --run "python-package-init mypackage"`. This exactly. What are your thoughts on need to publish to pypi? To make distribution easier (and I'm lazy) I'm leaning towards not. I will be adding some tests as well.

**Comment by costrouc** [comment]
@makefu yeah lets transfer the repo. What is the correct way to do this? Do I need creation permissions on nix-community? https://help.github.com/en/articles/transferring-a-repository#repository-transfers-and-organizations. I can also make you a collaborator on the repo

**Comment by makefu** [comment]
@costrouc i think you need create access, but you can make me (or anyone of nix-community) a repo owner and then i can do the move.

Regarding pypi, we could test out the new github CI features ([Github Flow]( https://guides.github.com/introduction/flow/ )) and see how well it can be integrated into the workflow.
If we cannot publish automatically then we should not publish at all :)

**Comment by makefu** [comment]
@costrouc you are now member of nix-community (Thanks @Mic92 !)

**Comment by costrouc** [comment]
Great thank you @makefu I have as you can tell transfered it to nixpkgs-pytools in the nix-community. Could you change the title to the repository to have " [maintainer=@costrouc]". I don't seem to be able to do that.

**Comment by makefu** [comment]
@costrouc but you still have push permissions, right? the transfer stuff is really weird it seems, acording to the documents i would have guessed you stay admin for the repo.

**Comment by costrouc** [comment]
Yes I just checked now and I do have admin permissions thanks! I would consider this closed.
