### ISSUE TITLE
Add nixpkgs-pytools to nixpkgs

### ISSUE THREAD

**Issue by costrouc** [nix-community/nixpkgs-pytools#8]

**Comment by makefu** [comment]
the first official Release in pypi has been created! https://pypi.org/project/nixpkgs-pytools/

**Comment by makefu** [comment]
That means we can now bootstrap our own tool release: 
```
$(nix-build shell.nix --no-out-link)/bin/python-package-init nixpkgs-pytools
```

**Comment by costrouc** [comment]
PR created in nixpkgs https://github.com/NixOS/nixpkgs/pull/59279

**Comment by costrouc** [comment]
Closing as PR was merged.
